#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

print 'Welcome to JudgeShop CLI version!'
print 'Command line: [JudgeShop] [problem pack name] [problem id] [source file name]\n'

if len(sys.argv) != 4:
    print 'Error: Arguments invalid.'
    sys.exit()

pack        = sys.argv[1]
prob_id     = sys.argv[2]
source_file = sys.argv[3]

from common import judge
result = judge(pack_source, prob_id, filename)
print result
